# -- AtomiCloud Service Tree. See [ServiceTree](https://atomicloud.larksuite.com/wiki/OkfJwTXGFiMJkrk6W3RuwRrZs64?theme=DARK&contentTheme=DARK#MHw5d76uDo2tBLx86cduFQMRsBb)
serviceTree:
  landscape: entei
  platform: sulfoxide
  service: radon
  layer: "1"

apps:
  nitroso:
    zinc:
      repoURL: ghcr.io/atomicloud/nitroso.zinc
      chart: root-chart
      landscapes:
        pichu: ^1.25.4
        pikachu: ~1.25.4
        raichu: 1.25.4
    tin:
      repoURL: ghcr.io/atomicloud/nitroso.tin
      chart: root-chart
      landscapes:
        pichu: ^1.25.1
        pikachu: ~1.25.1
        raichu: 1.25.1
    helium:
      repoURL: ghcr.io/atomicloud/nitroso.helium
      chart: root-chart
      landscapes:
        pichu: ^1.12.2
        pikachu: ~1.12.2
        raichu: 1.12.2
  sulfone:
    zinc:
      repoURL: ghcr.io/atomicloud/sulfone.zinc
      chart: root-chart
      landscapes:
        pichu: ^1.16.3
        pikachu: ~1.16.3
        raichu: 1.16.3