# -- AtomiCloud Service Tree. See [ServiceTree](https://atomicloud.larksuite.com/wiki/OkfJwTXGFiMJkrk6W3RuwRrZs64?theme=DARK&contentTheme=DARK#MHw5d76uDo2tBLx86cduFQMRsBb)
serviceTree:
  landscape: entei
  platform: sulfoxide
  service: radon
  layer: "1"

apps:
  nitroso:
    zinc:
      repoURL: ghcr.io/atomicloud/nitroso.zinc
      chart: root-chart
      landscapes:
        pichu: ^1.17.2
        pikachu: ~1.17.2
        raichu: 1.17.2
    tin:
      repoURL: ghcr.io/atomicloud/nitroso.tin
      chart: root-chart
      landscapes:
        pichu: ^1.10.0
        pikachu: ~1.10.0
        raichu: 1.10.0
    helium:
      repoURL: ghcr.io/atomicloud/nitroso.helium
      chart: root-chart
      landscapes:
        pichu: ^1.9.3
        pikachu: ~1.9.3
        raichu: 1.9.3
  sulfone:
    zinc:
      repoURL: ghcr.io/atomicloud/sulfone.zinc
      chart: root-chart
      landscapes:
        pichu: ^1.16.3
        pikachu: ~1.16.3
        raichu: 1.16.3