# -- AtomiCloud Service Tree. See [ServiceTree](https://atomicloud.larksuite.com/wiki/OkfJwTXGFiMJkrk6W3RuwRrZs64?theme=DARK&contentTheme=DARK#MHw5d76uDo2tBLx86cduFQMRsBb)
serviceTree:
  landscape: entei
  platform: sulfoxide
  service: radon
  layer: "1"

apps:
  nitroso:
    zinc:
      repoURL: ghcr.io/atomicloud/nitroso.zinc
      chart: root-chart
      landscapes:
        pichu: ^1.8.2
        pikachu: ~1.8.2
        raichu: 1.8.2
    tin:
      repoURL: ghcr.io/atomicloud/nitroso.tin
      chart: root-chart
      landscapes:
        pichu: ^1.2.5
        pikachu: ~1.2.5
        raichu: 1.2.5
    helium:
      repoURL: ghcr.io/atomicloud/nitroso.helium
      chart: root-chart
      landscapes:
        pichu: ^1.4.5
        pikachu: ~1.4.5
        raichu: 1.4.5
  sulfone:
    zinc:
      repoURL: ghcr.io/atomicloud/sulfone.zinc
      chart: root-chart
      landscapes:
        pichu: ^1.16.1
        pikachu: ~1.16.1
        raichu: 1.16.1