{{- range $k, $v := .Values.apps }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "{{ $k }}"
  annotations: {{- include "sulfoxide-radon.annotations" $ | nindent 4 }}
  labels: {{- include "sulfoxide-radon.labels" $ | nindent 4 }}
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                {{ range $service, $serviceConfig := $v.services -}}
                {{- range $landscape, $revision := $serviceConfig.landscapes}}
                - landscape: "{{ $landscape }}"
                  serviceName: "{{ $service }}"
                  repoURL: "{{ $serviceConfig.repoURL }}"
                  chart: "{{ $serviceConfig.chart }}"
                  revision: "{{ $revision }}"
                {{- end -}}
                {{- end }}
          - clusters:
              selector:
                matchLabels:
                  atomi.cloud/cluster-type: 'virtual'
                  atomi.cloud/cluster-landscape: "{{ `{{landscape}}` }}"
                  atomi.cloud/enable-appset: "true"
  template:
    metadata:
      name: '{{ `{{nameNormalized}}` }}-{{ $k }}-{{ `{{serviceName}}` }}'
    spec:
      project: "{{ $k }}"
      source:
        repoURL: "{{ `{{repoURL}}` }}"
        targetRevision: "{{ `{{revision}}` }}"
        helm:
          valueFiles:
            - values.yaml
            - "values.{{ `{{landscape}}` }}.yaml"
        chart: "{{ `{{chart}}` }}"
      destination:
        server: '{{ `{{server}}` }}'
        namespace: "{{ $k }}"
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
{{- end }}