poller:
  replicaCount: 3
  appSettings:
    buffers:
      closing: 60
    poller:
      pollee:
        version: "1.14.0"
enricher:
  replicaCount: 1
reserver:
  replicaCount: 6
  appSettings:
    buffers:
      closing: 60
    stream:
      reserver: buyqueue

buyer:
  appSettings:
    buyer:
      sleepBuffer: 7
    stream:
      reserver: buyqueue
