poller:
  replicaCount: 3
  appSettings:
    poller:
      pollee:
        version: "1.12.1"
enricher:
  replicaCount: 1
reserver:
  replicaCount: 6
  appSettings:
    buffers:
      closing: 60
    stream:
      reserver: buyqueue

buyer:
  appSettings:
    buyer:
      sleepBuffer: 7
    stream:
      reserver: buyqueue

pollers:
  replicaCount: 1
  appSettings:
    buffers:
      closing: 60
