poller:
  appSettings:
    poller:
      pollee:
        version: "1.12.1"

reserver:
  replicaCount: 6
  appSettings:
    buffers:
      closing: 60
    stream:
      reserver: buyqueue

buyer:
  appSettings:
    stream:
      reserver: buyqueue

pollers:
  appSettings:
    buffers:
      closing: 60
