poller:
  replicaCount: 2
  appSettings:
    buffers:
      closing: 60
    poller:
      pollee:
        version: '1.19.0'
enricher:
  replicaCount: 1
reserver:
  replicaCount: 7
  appSettings:
    buffers:
      closing: 60
    stream:
      reserver: buyqueue

buyer:
  appSettings:
    buyer:
      sleepBuffer: 1
    stream:
      reserver: buyqueue
